export const ROUTES = {
  home: '/',
  storefront: '/store',
  products: '/products',
  brand: (slug: string) => `/products/${slug}`,
  product: (slug: string) => `/products/${slug}`,
  cart: '/cart',
  checkout: '/checkout',
  orderConfirmation: '/order-confirmation',
  quote: '/quote',
  search: '/search',
  about: '/about',
  contact: '/contact',
  login: '/auth/login',
  register: '/auth/register',
  account: '/account',
  accountOrders: '/account/orders',
  admin: '/admin',
  adminInventory: '/admin/inventory',
} as const
